apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
  name: recommendationentry
  namespace: istio-system
spec:
  severity: '"warning"'
  timestamp: request.time
  variables:
    source: source.labels["app"] | source.service | "unknown"
    user: source.user | "unknown"
    destination: destination.labels["app"] | destination.service | "unknown"
    responseCode: response.code | 0
    responseSize: response.size | 0
    latency: response.duration | "0ms"
  monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: "config.istio.io/v1alpha2"
kind: stdio
metadata:
  name: recommendationentryhandler
  namespace: istio-system
spec:
 severity_levels:
   warning: 1 # Params.Level.WARNING
 outputAsJson: true
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: recommendationlogentryrule
  namespace: istio-system
spec:
  match: destination.service == "recommendation.tutorial.svc.cluster.local"
  actions:
   - handler: recommendationentryhandler.stdio
     instances:
     - recommendationentry.logentry
